# syntax=docker/dockerfile:1

FROM golang:1.22 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG CMD_PATH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/bin/service ./cmd/ingestor

FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=builder /app/bin/service /service
USER 65532:65532
ENTRYPOINT ["/service"]
